---
title: "Convocatorias"
---

Revista Némesis de Ciencias Sociales abre el llamado para la recepción de artículos, ensayos y reseñas bibliográficas, que serán publicados en el Número XX de la revista, buscando aportes en la temática de *Futuros posibles ante las crisis del Siglo XXI*, donde se valora especialmente las contribuciones originales realizadas desde perspectivas críticas. En esta línea, se reciben aportes en las siguientes áreas:

**Política:** Procesos políticos, cercano a temas relativos al sistema político, como la representatividad, confianza en instituciones, partidos políticos, nuevas formas de participación política, entre otros.

**Sociedad:** Procesos sociales de las distintas sociedades, ya sean mundiales, latinoamericanas o bien la chilena, abordando temáticas como la estratificación social, características de la sociedad civil, participación ciudadana, movimientos sociales, entre otras. También se ocupa de ámbitos societales específicos, como por ejemplo el área de la salud, de la educación, del trabajo, entre otras.

**Cultura:** Fenómenos culturales, cercano a temas de construcción de identidades, imaginarios colectivos, cultura popular, medios de comunicación, hegemonía, entre otros.

**Economía:** Procesos económicos, cercano a temáticas como análisis sobre el desarrollo, determinantes económicos de la vida social, explotación laboral, distribución del ingreso, modelos productivos, entre otros.

**Teoría Social:** Teorización de nuestras sociedades contemporáneas. Esto puede ser, por un lado, buscando articular un relato o arquitectura teórica que interpreta estas en su conjunto, incluyendo sus esferas políticas, sociales, culturales y económicas.

En esta ocasión no habrá un plazo establecido de recepción de los manuscritos, pues se requiere flexibilidad ante las condiciones de trabajo en las que se encuentra la revista. Pero el Comité editorial se compromete a informar, durante los primeros 10 días de recepción del artículo, si es que el texto será revisado para su publicación en el número XIX, o en los próximos números de la revista.

**Comunicación del fallo editorial a los autores:** (Para los que sean declarados publicables para el número XIX) entre 15 y 30 días hábiles desde el momento de recepción del manuscrito. Fecha de publicación del número: *martes 15 de agosto de 2023*
