---
title: "Convocatoria XXI"
categories: "Convocatorias"
author: Dirección y Equipo Editorial Némesis
date: today
lang: es
about: 
  template: marquee
---
::: {.callout-note appearance="default"}
Para más información sobre el proceso de publicación y los términos de referencia revisar [las normas para autores](normas_autores.html).
:::

::: {.callout-important appearance="minimal" }

¡Revista Némesis invita a estudiantes, investigadores, profesionales y académicos de las ciencias sociales y disciplinas afines a enviar sus manuscritos (ensayos, artículos y reseñas) para la convocatoria de su Número XXI! Este año, la temática central será la digitalización y las nuevas tecnologías, a través de un enfoque multidisciplinario y amplio. Les incentivamos a que envíen sus manuscritos y, si tienen alguna consulta, a contactarnos a través de nuestro correo electrónico ([nemesis\@uchile.cl](mailto:nemesis@uchile.cl)) o nuestra cuenta en Instagram ([\@revistanemesis](https://www.instagram.com/revistanemesis/)). Cabe señalar que, si bien los ejes propuestos orientarán parte importante del número, se aceptarán colaboraciones de temática abierta. El plazo máximo para el envío de manuscritos es el **31 de marzo.** ¡No dudes en escribirnos!

:::

Durante la última década, se ha evidenciado un ritmo de desarrollo tecnológico vertiginoso. Avances en áreas como la computación, la inteligencia artificial, la ingeniería social o las tecnologías militares han transformado profundamente el cómo nos relacionamos y vivimos nuestro día a día en la actualidad. Este proceso se ha visto agudizado durante los cuatro años anteriores con la masificación de la inteligencia artificial generativa, disparando preocupaciones transversales en las ciencias sociales; relativas a su impacto, y a la forma en que podemos adaptarnos o reaccionar ante esta.

En su momento, se habló de una Segunda Revolución Industrial, que cambió la potencia bruta por el control y la minuciosidad en el empleo de la energía. Esto condujo a  producir máquinas autocontroladas o recursivas, que además funcionan complementariamente en complejos sistemas. Si en un primer momento se transformó el trabajo físico, en la actualidad —a veces llamada “era de la información” (Castells, 2005)— se inaugura la posibilidad de externalizar funciones cognitivas. De hecho, tan temprano como en 1842 la matemática Ada Lovelace especuló sobre la idea de que las máquinas podrían dedicarse a tareas complejas fuera de la matemática, como la creación musical y científica. Esta pionera idea se materializó en 1943, cuando se crearon las primeras redes neuronales artificiales. Durante el *boom* de la cibernética en los años 50’, muchos de sus desarrolladores postularon que el pensamiento no es una operación exclusiva de los seres humanos, ni tampoco de los seres vivos. En consecuencia, surge la hipótesis de que la inteligencia humana es replicable (Abeliuk y Gutiérrez, 2021). 

Hoy en día, la construcción del conocimiento técnico y científico está estrechamente ligada a una industria tecnológica, que gracias a un mercado mundial ha llevado las innovaciones hasta lugares recónditos. Además del plano físico, ahora nos vemos conectados por todo un ecosistema digital, a veces mal conocido como “nube”, compuesto por una serie de sistemas informativos y comunicacionales que al día de hoy son capaces de recorrer — prácticamente — todo el mundo, dando pie al almacenamiento de cantidades inimaginables de datos en *Data Centers* controlados por las grandes empresas tecnológicas. De esta forma, grandes élites económicas en Silicon Valley y las ciudades industriales de Asia ya no solo controlan capitales bursátiles ni recursos naturales, sino infraestructura crítica para cualquier ser humano el día de hoy, y millones de datos sobre casi cualquiera que se creó alguna vez una cuenta de correo. 

En el siglo XXI, esta nueva empresa tecno-científica y económica ha testeado sus propios límites. La disponibilidad a datos masivos (*Big Data*) ocasionada por la masificación del internet, sumado a los avances recientes del hardware y de la investigación en frontera en *machine learning* posibilitaron la aparición de Grandes Modelos de Lenguaje (LLMs por sus siglas en inglés) con capacidades nunca antes vistas: ya no podían solo indicar el clima o poner una canción (como Siri o Alexa en el pasado), sino resolver problemas matemáticos, planificar y programar sistemas algorítmicos/computacionales y entender el lenguaje en su contexto respondiendo de forma similar a un humano. La Inteligencia Artificial (en adelante IA) se suma a un conjunto de nuevas tecnologías, desencadenadas por el salto en el desarrollo técnico, cuyo impacto global ya se registra desde lo ecológico a lo cultural y biopsicosocial. 

Muchas son las áreas que se han visto alteradas por el ingreso de la IA y otras tecnologías al mercado. Una de las más afectadas es el mundo del trabajo: a la conocida automatización de la mano de obra se suma hoy la ‘uberización’, un nuevo modo de empleo que surge con plataformas de trabajo temporal (o *gig economy*) como Uber, Airbnb o Rappi, donde las plataformas se limitan al plano virtual, externalizando los costos del trabajador (Durand, 2021). En contraste con lo que se pensaba en un pasado, entre las profesiones más afectadas por las últimas transformaciones tecnológicas se encuentran las normalmente asociadas a la creatividad y la capacidad de abstracción. A día de hoy, muchos profesionales se apoyan en la IA tanto para tareas triviales como para tomar decisiones relevantes, y diferentes empresas e instituciones buscan automatizar procesos como el análisis de datos, la programación, e incluso el arte o el diseño. 

La educación también ha recibido el impacto de las nuevas tecnologías. Hoy en día instituciones educativas en todo el mundo se preguntan cómo lidiar con el cambio. Recientemente, las pruebas del Programa para la Evaluación Internacional de Estudiantes (PISA, por sus siglas en inglés) (OECD, 2023) reportan una disminución en las capacidades de los estudiantes en todas las áreas desde los 2000, especialmente en el período post-pandemia. Aún está por verse el efecto que tendrá la llegada de la IA en estos indicadores. Pese a la enorme disponibilidad de información y herramientas para el aprendizaje autónomo, las instituciones tienen limitaciones para adaptarse a estos cambios, hecho resaltado por la pandemia por COVID-19, donde muchos profesores y estudiantes fueron forzados a adaptarse al formato online ya asincrónico.

Los viejos mapas están quedando obsoletos, y las ciencias sociales corren el riesgo de aplicar esquemas anacrónicos si no se vuelven a pensar incluso las categorías para comprender sus objetos de estudio. No es raro, entonces, que el pensamiento contemporáneo haya descrito el presente utilizando términos que aluden a la tecnología y su impacto en la realidad, sugiriendo una hipertrofia o sobredesarrollo de este aspecto. Algunos abordajes sugieren que el ser humano ve en las máquinas una forma de acceso al poder y el control, que la tecnología es idolatrada, que estamos siendo subyugados a esta o que los límites entre humanos y máquinas se vuelven crecientemente difusos. Entonces, el ser humano

::: {style="margin-left: 1.27cm;"}
busca construir la máquina de pensar, soñando con poder construir la máquina de querer, la máquina de vivir, para quedarse detrás de ella sin angustia, libre de todo peligro, exento de todo sentimiento de debilidad, y triunfante de modo mediato por lo que ha inventado. (Simondon, 2007, p. 32)
:::

El siglo XXI ha visto una transformación tecnológica-social sin precedentes, y exige detenimiento para observarla. El rol inédito que la tecnología digital tiene en todos los aspectos de la vida es lo que produce un llamado a su estudio para todas las disciplinas de las ciencias sociales. Es por ello que el número XXI de Némesis propone como temática este año la digitalización y la emergencia de nuevas tecnologías, invitando a pensar críticamente sobre este nuevo presente histórico.

#### Ejes propuestos:


1.  **Tecnología y educación:** Tecnologías de la Información y la Comunicación (TIC) y su efecto en los distintos procesos y resultados de aprendizaje; adopción, uso, actitudes, creencias y percepciones sobre TIC de estudiantes y profesores; Entornos Virtuales de Aprendizaje (EVA); gamificación; IA y nuevos desarrollos pedagógicos.

2.  **Tecnología, política y poder:** técnica y economía política; digitalización en un nuevo ciclo de acumulación capitalista; soberanía y gobernabilidad digital; resistencias en medios digitales; software libre y *open source*.

3.  **Tecnología y medioambiente:** sustentabilidad y continuidad de las tecnologías en términos ecológicos; rol de los recursos naturales y el impacto de su uso en grupos sociales; impacto socioambiental de infraestructura tecnológica crítica (e.g. *data centers*).

4.  **Tecnología, subjetividad, conducta y cognición:** modelos de cognición situada, extendida y distribuida; impacto neurobiológico de la digitalización; identidades y comportamientos digitales.

5.  **Tecnología, comunicación y socialización:** redes sociales y medios digitales; *fake news* y desinformación.

6.  **Tecnología y trabajo:** impacto de la IA en el trabajo; teletrabajo y salud mental; psicodinámica laboral en un contexto de digitalización; tecnoestrés.

7.  **Tecnología y género:** crítica feminista de la racionalidad tecno-científica; ciberfeminismo y tecnofeminismo.

8.  **Tecnología, salud, bienestar y cuidados:** vida familiar y relaciones comunitarias; hallazgos psicopatológicos y epidemiológicos característicos de la era digital; nuevos medios y técnicas de acompañamiento e intervención (e.g. atención remota, aplicaciones móviles, modelos de realidad aumentada, etcétera).

9.  **Tecnología y teorías críticas:** colonialismo y extractivismo digital; apropiaciones locales de tecnologías globalizadas; dilemas éticos relacionados a nuevas tecnologías.

10. **Tecnología y desigualdades:** brechas y desigualdades en el contexto de la sociedad digital; *digital divide* en accesos, usos, actitudes, alfabetización, creencias y resultados a través de distintos grupos sociales (género, estatus migrante, grupos etarios, clase social, entre otros).

11. **Construcción social de la tecnología y construcción tecnológica de la sociedad:**  Ciencia, Tecnología y Sociedad (CTS); análisis de procesos técnicos y científicos; estudios de ensambles o sistemas socio-técnicos y su impacto en fenómenos sociales.

12. **Tecnología y cultura:** políticas, economías e industrias culturales en la era digital; enclaves afectivos y política cultural de las emociones; hegemonías y resistencias digitales; comunidades, estéticas e identidades en entornos virtuales.

13. **Tecnología y economía:** *gig economy*, impactos económicos de la inteligencia artificial y la transformación digital; impacto  de las empresas desarrolladoras de nuevas tecnologías en la bolsa de valores; la burbuja bursátil de la IA.\

**Referencias**

::: {style="margin-left: 0.5in;  text-indent: -0.5in;"}
Abeliuk, A., & Gutiérrez, C. (2021). Historia y evoluación de la inteligencia artificial. Revista Bits de Ciencia, (21), 14-21.

Castells, M. (1999). La era de la información: Economía, sociedad y cultura. Siglo XXI.

Durand, C. (2021). Tecnofeudalismo: Crítica de la economía digital. La Cebra.

OECD (2023), PISA 2022 Results (Volume I): The State of Learning and Equity in Education, PISA, OECD Publishing, Paris, <https://doi.org/10.1787/53f23881-en>.

Simondon, G. (2007). El modo de existencia de los objetos técnicos. Prometeo Libros.
:::