---
title: Productos de trabajo
---

La lógica de conformar un Comité Editorial para abrir una convocatoria general a artículos académicos, y luego llevar a cabo un complejo proceso burocrático de revisión de pares que ha tenido la Revista en los últimos años, sin dudas que ha permitido aumentar la rigurosidad de los textos que son publicados, pero por todo lo dicho anteriormente, el trabajo se queda corto cuando uno solo se conforma con eso.

Antes que una agrupación de "expertos", el Comité Editorial debe actuar como un agente que intervenga en la facultad, atreviéndose a desarrollar actividades públicas en ella, que creen valor como comunidad de cientistas sociales que somos. Quienes levantan Némesis tienen que comprender que el número es solo la condensación final de todo el trabajo que se viene gestando durante el año, y en ese sentido, lo pulcro que termine dependerá del proceso, no de las condiciones finales del resultado.

El modelo de trabajo que pienso desplegar implica generar una ramificación de productos diferenciados que durante el año se irán publicando, ya sea en redes sociales, ya sea a través de una intervención física en la FACSO, para luego acumular escritos e instancias, que terminen siendo incluidas en el número final. En complemento, estarían las convocatorias generales de artículos académicos y otros varios.

A continuación, se presentan los productos que a mi parecer mejor permitirían la realización de esta idea.

### Artículos Académicos y Ensayos.

En los artículos académicos y ensayos se encuentra la piedra angular del número. Corresponde a investigaciones conceptuales o empíricas sobre temas relevantes para el debate público y la disciplina sociológica, que colinden entre las 5.000 y 7.000 palabras. Se espera desarrollar dos secciones distintas. La primera estaría reservada para publicar "Dossier" del tema que se esté trabajando en el número, y la segunda para una convocatoria abierta a artículos con temáticas generales. Todos los semestres se hace un "call for papers" en Redes Sociales, y una vez recibidos los aportes, se someten a un proceso de revisión por pares que está sedimentado por las y los anteriores líderes de la Revista.

### Comentarios bibliográficos

La presente sección estaría abierta a quienes quieran proporcionar reflexiones críticas de libros de Ciencias Sociales recientes al público. Se espera acumular unas 5 o 6 reseñas de textos actuales para invitar al resto de estudiantes de la facultad a sumergirse en las ideas y debates que vive el campo de la sociología. Tendría una extensión de no más de 3.500 palabras, y para apurar procesos, podría estar escrita por les mismes integrantes del Comité Editorial. Se priorizan las reseñas que estén relacionadas al tema del número del producto principal.

### Entrevistas

La sección de entrevistas proporciona una perspectiva experta y única sobre temas relevantes en el campo de estudio de las Ciencias Sociales. Puede incluir preguntas sobre la experiencia personal del entrevistado en el campo científico, su investigación actual o más reciente, su perspectiva sobre temas disciplinares, entre otros. Las entrevistas se transmiten, y luego queden grabadas en las redes sociales de Némesis. En el número del producto principal se publican las transcripciones de las entrevistas. Su duración máxima debería ser de 45 minutos. A veces el tema de la entrevista es el mismo que el de la sección dossier, de manera de hacer dialogar ambas cosas.

### Columnas de opinión

Existe un montón de estudiantes de la FACSO interesados en la contingencia sociopolítica. Es recurrente que entre este estamento se compartan puntos de vista y discusiones sobre lo que está ocurriendo en el momento de la facultad, el país o el mundo. Pero por mucho que se escribe, estos valiosos escritos de opinión quedan sin espacio de difusión formal. Por eso, Némesis entrega la posibilidad de recibir columnas de opinión respecto a los debates públicos y acontecimientos sociopolíticos relevantes para el estudiantado.

### Coloquio de tesistas

En la FACSO, los tesistas de pregrado se suelen sentir bastante solos cuando desarrollan sus investigaciones. Como es un proceso individual, en el cual uno se va desmarcando, incluso físicamente, del departamento de sociología, los únicos comentarios y observaciones críticas que se reciben provienen de le profesor guía. Hay poco contacto entre compañeres tesistas, siendo que podría ser un aporte enorme (emocional y académicamente) expandir los flujos de comunicación entre elles. Este producto se define como una presentación pública en el que unos 4 o 5 tesistas presentan en algún escenario de la facultad una ponencia, de no más de 10 minutos, al resto de estudiantes que estén alrededor. La idea es que esto permite a esos estudiantes hacerles preguntas y críticas que sirvan para ir fortaleciendo aún más sus trabajos. En términos procedimentales, se haría una convocatoria general a los tesistas de 5to año o más para que escriban un guión de 10 minutos de su presentación, y el Comité Editorial elegiría las ponencias que tengan mejor considerados. Cuando se publique la revista, se exponen en esta sección las ponencias seleccionadas.

### Notas investigativas

La investigación en Ciencias Sociales es un proceso dinámico, flexible e inacabado. En muchas ocasiones las horas de trabajo y reflexión nos llevan a almacenar ideas y resultados preliminares que una vez finalizada la investigación nunca ven la luz. Para promover la comprensión del cientista social en toda su complejidad, Némesis abre el espacio para recibir "notas investigativas", en la que las y los estudiantes nos pueden compartir sus primeros acercamientos al fenómeno de estudio con el que se involucran. Se trata de escritos breves que den una idea de lo que han ido construyendo en sus estudios.

### Presentación de organizaciones e iniciativas estudiantiles

Tiene como objetivo destacar y promover a los grupos coordinados de estudiantes de la facultad para desarrollar algún objetivo que entregue valor público a la universidad. Puede incluir descripciones sobre sus misiones y objetivos, reseñas de eventos y actividades pasadas, así como información sobre cómo los estudiantes pueden unirse a estas organizaciones. En la facultad suele haber cierta confusión sobre los trabajos que hacen las organizaciones, y esta sección puede ser una herramienta útil para las organizaciones, en tanto permite aumentar su alcance y visibilidad, y para los estudiantes que buscan formas de involucrarse en la comunidad universitaria, en tanto facilita su consciencia de las oportunidades disponibles para involucrarse en actividades extracurriculares y en la sociedad en general. Sería una sección corta de no más de 500 palabras por organización. Puede incluir logo y contactos.
