---
title: "Comentarios bibliográficos"
lang: es
category: "no_visualize"
listing:
  contents: comentarios
  type: default
  sort: date desc
  feed: true
  fields: [date, title, author, reading-time, description, image]
  filter-ui: true
  page-size: 10
  image-align: left
  image-height: 15.0rem
  image-placeholder: ../../images/comentarios_dalle.png

page-layout: full
---

La presente sección está abierta para quienes quieran proporcionar reflexiones críticas de libros de Ciencias Sociales recientes al público. Se espera acumular reseñas de textos actuales (con menos de 10 años de antigüedad) para invitar al resto de estudiantes de la facultad a sumergirse en las ideas y debates que vive el campo de las ciencias sociales.

El envío de reseñas debe ser vía el siguiente [formulario](https://docs.google.com/forms/d/e/1FAIpQLSdg4NTkgWBJO0Ah9Q3VMkudxJxrMIab5dEH-MCXGSH8m9lZCg/viewform?usp=sf_link), teniendo que completar los distintos apartados y adjuntar el manuscrito en el formato indicado.

En términos de extensión, pueden variar entre las **1000 y 3000 palabras**. Se priorizarán textos actuales, o sea, con **menos de 10 años de longevidad**.

A finales de año, el Comité editorial de Némesis se reune para seleccionar los mejores comentarios bibliográficos para publicarlos en el próximo número de la revista.
